a = input('Digite algo: ')
print('É um espaço:', a.isspace())
print('É uma string:', a.isdigit())
print('É uma letra:', a.isalpha())
print('É numérico:', a.isnumeric())
print('É alfanumérico:', a.isalnum())
print('É minúscula:', a.islower())
print('É maiúscula:', a.isupper())
print('Está capitalizada :', a.istitle())