#Letra
a1 = input('Escolha uma letra: ')
a2 = int(input('Escolha um número 1 a 9: '))
print(f'Sua letra pode ser multiplicada: {a1*a2}')
print(27*'=')
#Operadores:
a3 = int(input('Escolha um número: '))
a4 = int(input('Escolha uma soma: '))
a5 = int(input('Escolha um multiplicador: '))
a6 = int(input('Escolha uma potência: '))
c = (a5*(a3+a4)**a6)
print(27*'=')
print(f'A questão programada, foi: ({a5}*({a3}+{a4})**{a6})')
print(f'O resultado é: {c}')

print('Agora escolha um número para dividir esse valor:')
a7 = int(input('>> '))
d = (c//a7)
e = (c%a7)
print(27*'=')
print('O resultado inteiro é:', d)
print('E a sobra é:', e)
print(27*'=')
print('E só pra não esquecer a raiz quadrada...')
print(f'O resultado de {c}, seria: {c**(1/2):.3f}')