#22: input('').strip() , len(v)-v.count(" ")
a1 = input('Qual seu nome? ').strip()
print(f'Nome todo maiúsculo: {a1.upper()}')
print(f'Nome todo minúsculo: {a1.lower()}')
print(f'Seu nome tem um total de {len(a1)-a1.count(" ")} letras.')
b1 = a1.split()
print(f'Seu primeiro nome é {b1[0]}, e tem {len(b1[0])} letras.')
input('NEXT:===')
#23: %10
a2 = int(input('Digite um número de 0 a 9999: '))
print(f'Unidade: {a2 // 1%10}')
print(f'Dezena: {a2 // 10%10}')
print(f'Centena: {a2 // 100%10}')
print(f'Milhar: {a2 // 1000%10}')
input('NEXT:===')
#24: ==
a3 = str(input('Digite o nome do seu estado: ')).strip()
b1 = (a3.upper()[:5] == 'SANTA')
print(f'Você nasceu em Santa Catarina? {b1}')
input('NEXT:===')
#25: 'str'in v.lower()
a4 = str(input('Qual seu nome? ')).strip()
print(f'Seu nome possui Silva? {"silva"in a4.lower()}')
input('NEXT:===')
#26: v.rfind('str')+1
a5 = str(input('Digite uma frase: ')).strip().upper()
print(f'Tem {a5.count("A")} letras "a".')
print(f'O primeiro "a", está na casa: {a5.find("A")+1}')
print(f'O ultimo "a", está na casa: {a5.rfind("A")+1}')
input('NEXT:===')
#27: v[len(v)-1]
a6 = input('Qual seu nome? ')
a6 = a6.split()
print(f'Seu primeiro nome é: {a6[0]}')
print(f'Seu último nome, é: {a6[len(a6)-1]}')
input('FINISH:===')
print('='*27,'\n','Linha de comando finalizada!','\n','='*27)